### ISSUE TITLE
Isodate Fails To Install

### ISSUE THREAD

**Issue by kchason** [casework/case#106]
# Bug description
`requirements.txt` identifies a requirement for `isodate==0.5.4` which utilizes calls `use_2to3` which is incompatible with `setuptools` > v58.
[https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2](https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2)

This causes the installation `pip install -r requirements.txt` to fail as `isodate` cannot be installed.

## Steps to reproduce

- Install `setuptools` > v58 (`pip install setuptools=59.0.0`)
- `pip install -r requirements.txt`

# Coordination

- [x] [Implementation](https://github.com/casework/CASE/pull/107) merged into `develop`
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by ajnelson-nist** [comment]
On review, the actual issue is that CASE has a `/requirements.txt` file that is quite stale, and should just be removed.

Thanks for reporting this!
