### ISSUE TITLE
Ability to identify byte offsets for carved data

### ISSUE THREAD

**Issue by mike-parkhill** [casework/case#27]
In order to support items that are found via "carving" the standard needs a way to represent the found location of the object with respect to byte offsets from the containing file space (e.g. unallocated, unpartitioned, file slack, etc.).

I'm just getting familiar with what's here, so forgive me if I've overlooked this.

**Comment by sbarnum** [comment]
Mike, you may want to check out the following example.

[bulk_extractor_forensic_path.json](https://github.com/casework/case/blob/master/examples/bulk_extractor_forensic_path.json)

Pay particular attention to the DataRange property bundles on the Relationships between the objects and their containing objects.
It sounds like this is what you are looking for.

**Comment by mike-parkhill** [comment]
Ah,okay.  Do you have examples of using the relationship for showing where in a database (e.g. sqlite) information was found?  What about scenarios where the data is aggregated from different locations?

**Comment by sbarnum** [comment]
you may want to take a look at the "relationship4" object within:
[file.json](https://github.com/casework/case/blob/master/examples/file.json)

As far as data aggregated from different locations I would suggest looking at:
[reconstructed_file.json](https://github.com/casework/case/blob/master/examples/reconstructed_file.json)
