### ISSUE TITLE
bulk_extractor_forensic_path.json: kindOfRelationship on two relationships should be "decompressed-from" rather than "contained-within"

### ISSUE THREAD

**Issue by sbarnum** [casework/case#6]
In bulk_extractor_forensic_path.json, kindOfRelationship on Relationship3 and Relationship5 should be “decompressed-from” not “contained-within".

decompressions, decodings and decryptions are not containment relationships. They are mathematical transforms of the same information.

**Comment by casework** [comment]
I may be missing something here, but I don't fully understand the need for having different keywords for file relationships. From a deserialization standpoint, the program is going to completely ignore this keyword and use the property bundles defined in the relationship object to understand how to traverse from the target to the source, ie, duck typing. For example, a Compression PB indicates a decompression is in order, Entryption PB indicated decryption, and PathRelation PB indicated traversing a path. The keyword is only used so it can quickly query for file relationship objects. Having a single keyword would make it simplier for the serializer.

If the mulitple keywords is needed for another reason that's fine. It's just not needed for the serializer to do its job.

I'll change this in any case.
