### ISSUE TITLE
Reconstructed_file: On “reconstructed_file” object, the “size” property should be “sizeInBytes” and the “data” property should be “dataPayload"

### ISSUE THREAD

**Issue by sbarnum** [casework/case#9]
On “reconstructed_file” object, the “size” property should be “sizeInBytes” and the “data” property should be “dataPayload"

**Comment by casework** [comment]
Fixed in pull request: https://github.com/casework/case/pull/5/files#diff-59a510a79448c1d5c1be48f6afca3068

**Comment by casework** [comment]
Nvm, I see some I missed.
