### ISSUE TITLE
Update CASE examples which reference tool.ttl Facet 'ToolConfigurationTypeFacet' (previously named 'ToolConfigurationTypeFacet')

### ISSUE THREAD

**Issue by gwebb-case** [casework/case#97]
# Background

# Requirements
Remove the text "Type" from the UCO ontology for the following Facet:

-  tool.ttl:ToolConfigurationTypeFacet

so that it becomes

- tool.ttl:ToolConfigurationFacet

## Requirement 1
Replace all occurances of the text "ToolConfigurationTypeFacet" with "ToolConfigurationFacet"
e.g. *.replace(current="ToolConfigurationTypeFacet", new="ToolConfigurationFacet")
within the:

- <a href="https://github.com/ucoProject/UCO/blob/master/ontology/tool/tool.ttl">tool.ttl file (current)</a>
<pre style="font-size: 12pt;">  359   tool:ToolConfiguration<b><u><span color="red">Type</span></u></b>Facet
                          :
  365	    rdfs:label "ToolConfiguration<b><u><span color="#ff000">Type</span></u></b>Facet"@en ;
                          :
  379       sh:targetClass tool:ToolConfiguration<b><u>Type</u></b>Facet ;      </pre>

- <a href="https://github.com/ucoProject/UCO/blob/master/ontology/tool/tool.ttl">tool.ttl file (after change)</a>
<pre style="font-size: 12pt;">  359   tool:ToolConfigurationFacet
                          :
  365	    rdfs:label "ToolConfigurationFacet"@en ;
                          :
  379       sh:targetClass tool:ToolConfigurationFacet ;      </pre>

  ## Requirement 2
Check all examples within the master branch of:
&nbsp;<a href="https://github.com/casework/CASE-Examples/tree/master/examples/">https://github.com/casework/CASE-Examples/tree/master/examples/</a>

for any references affected by the change.
i.e. run a keyword search across all the files in the above folder, and all its sub-folders, for "ToolConfigurationTypeFacet" 
Known changes:

- <a href="https://github.com/casework/CASE-Examples/blob/master/examples/illustrations/configured_tool/configured_tool.json">master/examples/illustrations/configured_tool/configured_tool.json</a> (3 changes)
<pre style="font-size: 12pt;">   24   {
   25       "@id": "kb:Tool-be707329-48fe-4d5d-84f3-7978ba63869e",
                        :
   35               "@type": "uco-tool:ToolConfiguration<b><u>Type</u></b>Facet",    </pre>

<pre style="font-size: 12pt;">   92   {
   93       "@id": "kb:Tool-f40e2a5f-7fdf-491f-8c87-b4cb766a6377",
                        :
  103               "@type": "uco-tool:ToolConfiguration<b><u>Type</u></b>Facet",    </pre>

<pre style="font-size: 12pt;">  160   {
  161       "@id": "kb:Tool-134e3cc0-7f74-4ea2-9ac1-3c447f4f6195",
                        :
  171              "@type": "uco-tool:ToolConfiguration<b><u>Type</u></b>Facet",    </pre>

- <a href="https://github.com/casework/CASE-Examples/blob/master/examples/illustrations/Oresteia/Oresteia.json">master/examples/illustrations/Oresteia/Oresteia.json</a> (2 changes)
<pre style="font-size: 12pt;"> 1110    {
 1111       "@id": "kb:tool2-uuid",
                        :
 1121               "@type": "uco-tool:ToolConfiguration<b><u>Type</u></b>Facet",   </pre>

<pre style="font-size: 12pt;"> 1172    {
 1173       "@id": "kb:tool3-uuid",
                   :
 1182               "@type": "uco-tool:ToolConfiguration<b><u>Type</u></b>Facet",    </pre>

# Risk / Benefit analysis

## Benefits
The changes provides better conformance with the standard CASE Facet guidance

## Risks
<ol>
    <li>Any developer code which currently hard codes the json-ld output using the existing "ToolConfigurationTypeFacet" name will need to amended to allow compability with future UCO\CASE versions.<br>
    <i>Note: Code which automatically generates output data directly from the versioned *.ttl files will be unaffected by the change.</i></li>
    <li>Forked examples may not, by default, have the change in their existing copy.</li>
</ol>

# Competencies demonstrated

After the change, re-run a text search across all the files in the following repositories:
<li> <a href="https://github.com/ucoProject/UCO">https://github.com/ucoProject/UCO (master)</a></li>
<li> <a href="https://github.com/casework/CASE-Examples">https://github.com/casework/CASE-Examples (master)</a></li>

### Competency Question 1.1
Check that no hits are generated for the text pattern "ToolConfigurationTypeFacet" (case insensitive)

#### Result 1.1
The result should not return any Hits

### Competency Question 1.2
Check that hits are generated for the text pattern "ToolConfigurationFacet" (case insensitive)

#### Result 1.2
Check that all hits are an exact match for "ToolConfigurationFacet" (case sensitive)
<ul>
    <li>tool.ttl (3 hits)</li>
    <li>configured_tool.json (3 hits)</li>
    <li>Oresteia.json (2 hits)</li>
</ul>

# Solution suggestion
Make the changes suggested above.

# Coordination

- Tracking in Jira ticket [OC-260](https://unifiedcyberontology.atlassian.net/browse/OC-260)
- [x] Administrative review completed
- [ ] Requirements to be discussed in OC meeting, [2022-08-16](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2035023880/2022-08-16+CDO+Ontology+Committees)
- [ ] Requirements Review vote has not occurred

- [ ] *Requirements development phase completed.*
- [ ] Solution announced to OCs on *(TODO-date)*
- [ ] Solutions Approval to be discussed in OC meeting, date TBD
- [ ] Solutions Approval vote has not occurred

- [ ] *Solutions development phase completed.*
- [ ] Implementation has not been merged into `develop`

- [ ] Milestone linked
- [ ] Documentation logged in pending release page

**Comment by gwebb-case** [comment]
Requirement 1, changing tool.ttl has been moved to UCO Ontology change request.

This change now only affects the updating of CASE examples, and is on hold until the UCO change has been approved and tool.ttl has been updated.

**Comment by ajnelson-nist** [comment]
@gwebb-case , thank you for filing this.

As a reminder to everyone, all ontology changes for UCO and CASE are reviewed against CASE examples as part of the [pull request merge checklist](https://github.com/Cyber-Domain-Ontology/cdo.github.io/blob/main/CONTRIBUTE.md#pull-request-review).

**Comment by ajnelson-nist** [comment]
@gwebb-case , I couldn't find where this had moved to in the UCO Github Issue tracker.  If it went into Jira, only a very few of us are using that for orchestration; otherwise, issues should be posted onto Github.

Due to Github technological issues, we can't migrate this issue to UCO's tracker.  We'll just try to process it in place here.

**Comment by ajnelson-nist** [comment]
Closing as migrated to [UCO Issue 451](https://github.com/ucoProject/UCO/issues/451).
