### ISSUE TITLE
Change minCount from 1 to 0 on multiple properties on Investigation object

### ISSUE THREAD

**Issue by eoghanscasey** [casework/case#98]
This is proposed as a FastTrack change

# Background
Most properties in CASE are optional. Setting minCount = 1 is enforced by SHACL makes a property required. This constraint will create problems in use cases in which a property is known to have existed but the value is not available.

# Requirements

## Requirement 1
Allow adopters to create an object when the existence of an object is known but an associated property is not known.

# Risk / Benefit analysis
The proposed change allows adopters to decide which property is needed, except when it is ontologically necessary.

## Benefits
Allow adopters to decide which property is needed.

## Risks
The submitter is unaware of risks associated with this change.

# Competencies demonstrated
Adopter creates an object when the existence of an object is known but an associated property is not known.

# Solution suggestion
Change minCount to 0 from 1 on the following Investigation properties:

- authorizationType
- authorizationIdentifier
- authorizationForm

# Coordination

- Tracking in Jira ticket [ONT-482](https://cyberontology.atlassian.net/browse/ONT-482)
- [x] Administrative review completed
- [x] Solutions Approval to be discussed in OC meeting, date [2022-08-16](https://cyberontology.atlassian.net/wiki/spaces/CDOC/pages/2035023880/2022-08-16+CDO+Ontology+Committees)
- [x] Solutions Approval vote occurred, not passing, on 2022-08-16
- [x] *Solutions development phase completed.*
- [x] [Implementation](https://github.com/casework/CASE/pull/104) merged into `develop`
- [x] Milestone linked
- [x] Documentation logged in pending release page

**Comment by plbt5** [comment]
@eoghanscasey Is it possible that you intended to change `investigationForm` as opposed to `authorizationForm`? I cannot find the latter, while the former is present in `investigation.ttl`. Please clarify; I've already changed the other two.

**Comment by eoghanscasey** [comment]
@plbt5 Yes, I did mean investigationForm. Thank you for this correction.

**Comment by plbt5** [comment]
@ajnelson-nist : Running `make check` throwed an error. Following your comment on rtf-toolkit [here](https://github.com/ucoProject/UCO/issues/432#issuecomment-1215772207), I was able to correct my local UCO clone as well. Thanks for providing that solution.

However, running the (now corrected) `make check` results in `2 passed, 1 xfailed`. Does that imply:

1. that one verification failed, or
2. that one falsification succeeded, i.e., success for all three?

**Comment by ajnelson-nist** [comment]
@plbt5 : I suppose the extra comment on `rdf-toolkit` is worth a more careful `make clean` rule to catch this issue.

`xfail` is considered a success - it is a test eXpected to Fail in a specific way, via targeted inducement.

**Comment by plbt5** [comment]
Well done! Then we're finished with this, so I'll turn it into a PR.
